from building import *
Import('pyenv')

cwd = GetCurrentDir()

objs = []
objs += Glob('*.cpp')

INCD = ['']
pyenv.Append(CPPPATH=['%s/%s'%(cwd,d) for d in INCD])
pyp = sys.executable
if(IsPlatformWindows()):
    pyp = pyp.replace(os.sep, '/')[:-10]
    pylib = 'python'+sys.version[0]+sys.version[2]
    pf = '%s/libs/lib%s.a'%(pyp, pylib)
    if(not os.path.exists(pf)):
        RunCommand('cp {0}/libs/{1}.lib {0}/libs/lib{1}.a'.format(pyp, pylib))
    pyenv.Append(CPPDEFINES=['_hypot=hypot'])
    pyenv.Append(CPPPATH=['%s/include'%(pyp)])
    pyenv.Append(LIBPATH=['%s/libs'%(pyp)])
else:
    pyp = os.sep.join(pyp.split(os.sep)[:-2])
    if(sys.version[0:3] == '2.7'):
        pylib = 'python'+sys.version[0:3]
    else:
        pylib = 'python'+sys.version[0:3]+'m'
    pyenv.Append(CPPPATH=['%s/include/%s'%(pyp,pylib)])
    pyenv.Append(LIBPATH=['%s/lib'%(pyp)])
pyenv.Append(LIBS=[pylib, 'stdc++', 'dl', 'm'])

Return('objs')
