from building import *
Import('pyenv')

cwd = GetCurrentDir()

objs = []
objs += Glob('*.cpp')

INCD = ['']
pyenv.Append(CPPPATH=['%s/%s'%(cwd,d) for d in INCD])
AddPythonDev(pyenv)

Return('objs')
