from building import *
Import('asenv')

cwd = GetCurrentDir()
tgt = '%s/models/date.o'%(cwd)
src = '%s/gen_models.py'%(cwd)
cmd = 'cd %s && python3 gen_models.py && date > %s'%(cwd, tgt)

MKObject(src, tgt, cmd)

asenv.Append(LIBS=['gtest','gtest_main','pthread','stdc++', 'dl', 'm'])

objs = Glob('*.cpp')
objsM = Glob('models/*/*.c')
for obj in objsM:
    asenv.SharedLibrary(obj)
Return('objs')
