/**
 * LWNN - Lightweight Neural Network
 * Copyright (C) 2019  Parai Wang <parai@foxmail.com>
 */

OP_DEF(INPUT)
OP_DEF(OUTPUT)
OP_DEF(MAXIMUM)
OP_DEF(CONV2D)
OP_DEF(RELU)
OP_DEF(MAXPOOL)
OP_DEF(RESHAPE)
OP_DEF(DENSE)
OP_DEF(SOFTMAX)
OP_DEF(PAD)
OP_DEF(DWCONV2D)
OP_DEF(CONCAT)
OP_DEF(AVGPOOL)
OP_DEF(ADD)
OP_DEF(CONST)
OP_DEF(DETECTIONOUTPUT)
OP_DEF(UPSAMPLE)
OP_DEF(YOLO)
OP_DEF(YOLOOUTPUT)
OP_DEF(DECONV2D)
OP_DEF(BATCHNORM)
