from building import *
Import('asenv')

cwd = GetCurrentDir()
print(cwd)

objs = []
objs += Glob('layers/*.c')
objs += Glob('runtime/*.c')
objs += Glob('runtime/cpu/*.c')
objs += Glob('runtime/cpu/*/*.c')
objs += Glob('runtime/opencl/*.c')
objs += Glob('*.c')

asenv.Append(CPPPATH=['%s/%s'%(cwd,d) for d in ['','layers','runtime']])

if(IsPlatformWindows()):
    asenv.AppendENVPath('PATH', os.getenv('PATH'))
    cuda = os.getenv('CUDA_PATH')
    asenv.Append(CPPPATH=['%s/include'%(cuda)])
    objs += ['%s/lib/x64/OpenCL.lib'%(cuda)]
else:
    asenv.Append(LIBS=['OpenCL'])

objs += SConscript('third_party/SConscript')

Return('objs')
